[
  uuid(6766CD0E-744E-4EEF-AFD4-A6F8C1761EA0)

]
library test
{

  importlib("stdole2.tlb");

  [uuid(1D5BF34D-2B3A-4B9A-AAB7-E693BBBDDBCE)]
  dispinterface IPureDisp {
    properties:
    methods:
      [id(1)]
      HRESULT _stdcall Disp1();
      [id(2)]
      HRESULT _stdcall Disp2([in] long AIdx);
      [id(3)]
      HRESULT _stdcall Disp3([out, retval] long * AIdx);
  }

  [uuid(6C190416-C4B8-47AD-8FB7-C5786B1A6B5C)]
  typedef struct {
    long Fld1;
  } TRec;

  [uuid(6FB81CFB-39D0-466A-8FB3-34F4869C31EE)]
  interface IBase: IDispatch {
    HRESULT _stdcall Base1([in] TRec ARec);
    HRESULT _stdcall Base2([in] GUID AVal);
  }

  [
    uuid(4ED7009C-0ABF-48A2-AED3-BDF3EF234281),
    dual
  ]
  interface IChild: IBase {
    HRESULT _stdcall Child();
  }

  [
    uuid(CD7ADC1B-BF0D-4B90-865E-A37D9839E613),
    dual
  ]
  interface IChild2: IChild {
    HRESULT _stdcall Child2();
  }

  [uuid(DCAD69DF-5D55-4236-A7C1-4EB5AC9FF2A3)]
  typedef BSTR myStr;

  [
    uuid(D3F8F5B4-E9AC-487B-8397-98E2EC44450D),
    oleautomation,
    dual
  ]
  interface ITest: IDispatch {
    long _stdcall Set([in] IUnknown * AVal);
    HRESULT _stdcall Get([out] IUnknown ** AOut);
    HRESULT _cdecl Owner([in] ITest * AOut);
    HRESULT _stdcall SetStr([out] long * B, [in] BSTR AVal);
    HRESULT _stdcall SetStr1([in] myStr AVal);
    HRESULT _stdcall Set0(BSTR AVal);
    HRESULT _cdecl Get0([out, retval] long * AVal);
    HRESULT _stdcall GetStr0([out] myStr AVal);
  }

  [
    uuid(8B19090D-3476-42CB-9510-DC497354E1DA),
    oleautomation,
    dual
  ]
  interface ITestProp: IDispatch {
    long _stdcall Set([in] IUnknown * AVal);
    [propget]
    HRESULT _stdcall Get([out] IUnknown ** AOut);
    [propput]
    HRESULT _cdecl Owner([in] ITest * AOut);
    [propget]
    HRESULT _cdecl Get0([out, retval] long * AVal);
    [propput]
    HRESULT _stdcall Get0([in] long AVal);
    [propget]
    long _cdecl Get1();
    [propput]
    void _cdecl Get1([in] long AVal);
    [propget]
    HRESULT _stdcall Get2([out, retval] long * AVal);
    [propput]
    HRESULT _stdcall Get2([in] long AVal);
    [propget]
    HRESULT _stdcall Get3([in] long AIdx, [out, retval] long * AVal);
    [propput]
    HRESULT _stdcall Get3([in] long AIdx, [in] long AVal);
  }

/*  [uuid(5FB032D3-FBAF-4C53-AFF2-2445476BCE07), dual]
  interface IrsTestDual: IDispatch {
    [id(1)]
    HRESULT _stdcall Info([out, retval] BSTR * AOut);
  }

  [uuid(C479589F-2226-45C8-8499-2DE1AA25C851)]
  dispinterface IrsTestDisp {
    properties:
    methods:
    [id(1)]
    HRESULT _stdcall Info([out, retval] BSTR * AOut);
  }

/*  [uuid(6A8BECCC-88A3-49FA-8BBD-B84CF49C5797)]
  dispinterface IrsTest2 {
    interface IrsTest;
  }
*/};
